version: '3.8'
services:
  gateway:
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
  server:
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURSE_URL=jdbc:postgresql://localhost:5432/shareit
      - SPRING_DATASOURSE_USERNAME=postgres
      - SPRING_DATASOURSE_PASSWORD=postgres
  db:
    image: postgres:14-alpine
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shareit